### ISSUE TITLE
fix the header  to be adaptable to small screens

### ISSUE THREAD

**Issue by MaguiRocha** [CatimaLoyalty/Website#20]
if you open the google devtools , you can see de bug

![catima proyect](https://user-images.githubusercontent.com/111162805/195955840-2f548e16-1ef2-4ced-9c10-f830f614c098.png)

it would be a pleasure for me to fix it!
Thank youu

**Comment by TheLastProject** [comment]
I thought this was fixed in #18 already but I guess it can still be improved further. If you think you can improve it, go ahead :)

**Comment by MaguiRocha** [comment]
I will do my best to improve them! Thank you very much!! ✨

**Comment by MaguiRocha** [comment]
Hi !
I need to ask you something, sorry if it's not the place, but it's my first hacktoberfest,
I can't find the html and style code of the error I sent you, I searched inside the repository, but I couldn't find it

**Comment by TheLastProject** [comment]
The website is built using [Jekyll](https://jekyllrb.com/).

The main page is [_layouts/default.html](https://github.com/CatimaLoyalty/Website/blob/master/_layouts/default.html). It includes several files from [_includes](https://github.com/CatimaLoyalty/Website/tree/master/_includes). Specifically, I think you're looking for [_includes/header.html](https://github.com/CatimaLoyalty/Website/blob/master/_includes/header.html).

The CSS is actually SASS and in [_sass](https://github.com/CatimaLoyalty/Website/tree/master/_sass), this is turned into CSS at build time.

**Comment by MaguiRocha** [comment]
Ah Ok :sob: 
I still don't know Jekyll, I hope to be able to collaborate with your projects next year!

**Comment by ngdangtu-vn** [comment]
@MaguiRocha You gave me a guity thought of stealing your job for the Fest. You don't need to know Jekyll for this, you only need to understand SCSS and an approved design for this case. About the design, I don't know if they have a design for this case. I can make a design patch for this case if @TheLastProject (which properly not) fire an issue for it and assign to me.

About the CSS, here is my tip for you:

![image](https://github.com/CatimaLoyalty/Website/assets/68631458/e511d72d-7b83-4d6b-8818-f5a9c1769050)

Follow the red line, you can see the file you need to modify is in `/_sass/layout.scss`. Try to mess around a bit more before giving up.

@TheLastProject can I patch your website design?

**Comment by TheLastProject** [comment]
I don't really have a design, I'm not a designer (I based the website onto the template of someone else), so I don't really have a real strong opinion on what is the best design. My first thought was to allow the header to become multiple lines if it doesn't fit so we can fit more things in it, but maybe a dropdown menu or so is better. If you have a suggested design I'd happily hear about it, it has been a year so sure you can have this assigned :)

**Comment by ngdangtu-vn** [comment]
Oh, too bad for her. Well what done is done. I will attempt to give you a simple menu on mobile design. And after you approve it, I'll start to fix the website.

**Comment by ngdangtu-vn** [comment]
Here is purpose patch design:

![image](https://github.com/CatimaLoyalty/Website/assets/68631458/baea37af-7b3f-43c6-8a8a-e32a0b243820)

This is common way to display main-menu in mobile. Familiar, and easy to build. I can do it at maximum a half day.

**Comment by TheLastProject** [comment]
Makes sense, it'll still use the old layout on desktop where there is enough space then?

**Comment by ngdangtu-vn** [comment]
Of course, no point to hide it in desktop :)

**Comment by TheLastProject** [comment]
Sounds great then :+1:

**Comment by ngdangtu-vn** [comment]
I'll do it then.

**Comment by obfusk** [comment]
This is pretty much what my own website does on mobile, so yeah LGTM.

**Comment by ngdangtu-vn** [comment]
This feature (without CSS hacking) requires JavaScript. And I don't how did you guy deal with JS. So how should I handle the JS? For now I can attempt to do:

1. HTML/CSS only → this way is ugly to SEO for sure 
2. JS without compressing → I'm doing this but it could harm website speed a little
3. Compressed JS → increase project complexity which is not making sense for deploy such a tiny feature like this.
4. Compress JS **manually** → I plan to write instruction on js file to tell dev upload this file to an online compression server to get min.js (I recommend this case for simple & open website)

What do you think, which do you prefer?

**Comment by ngdangtu-vn** [comment]
Also, how do you test site in localhost? I tried `bundle` and got this error:

```
An error occurred while installing http_parser.rb (0.8.0), and Bundler cannot continue.

In Gemfile:
  jekyll was resolved to 4.3.2, which depends on
    em-websocket was resolved to 0.5.3, which depends on
      http_parser.rb
```

**Comment by TheLastProject** [comment]
I don't really have a real JS policy because I'm not a web dev. But I'm thinking we can do a first version with the full JS file (because reviewing minified files for security is very hard so for third party contributions I'd rather avoid accepting minified JS) and then later figure out how to best automate JavaScript minification in Jekyll as a separate issue (then we can get rid of the .min.js for bwip too).

Sure, full JS is slightly slower than minified JS but the website is kept pretty minimal so I don't think most users will really notice any real difference so I find it more of a "nice to have" than "must have" to have it minified.

About testing locally, I'll be honest, I kinda gave up on that myself. Jekyll can be hellish to get running. Perhaps people more experienced with Jekyll can help: https://jekyllrb.com/docs/community/#where-to-get-support.

If that doesn't work, feel free to make a draft PR and then ping me in this issue when it's ready for review so I can ignore the emails but you can still make use of the temporary URL Netlify generates.

**Comment by obfusk** [comment]
> About testing locally, I'll be honest, I kinda gave up on that myself.

FWIW, I just temporarily delete the `Gemfile` and change `:compressed` to `compressed` in `_config.yml` and then it runs fine locally with the `jekyll` package from Debian for me :sweat_smile:

**Comment by ngdangtu-vn** [comment]
> > About testing locally, I'll be honest, I kinda gave up on that myself.
> 
> FWIW, I just temporarily delete the `Gemfile` and change `:compressed` to `compressed` in `_config.yml` and then it runs fine locally with the `jekyll` package from Debian for me 😅

Thanks but "it doesn't work on my machine" :9

**Comment by TheLastProject** [comment]
Fixed in f22194309f3d21b873f4e0c9b1d346b232703415
